markdown: kramdown
kramdown: 
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


#redcarpet
permalink: /post/:title.html
url: http://happyhacking.info
baseurl: http://happyhacking.info

lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: happyhacking.info
title: 碎碎念
description: 随手记下过往...
author: ch0psticks

config:
  js_dir:
  img_dir:
  css_dir:
